#ifndef TESTBUILDERS_WORKSHOP_TESTS_DOMAIN_COUNTRY_TEST_COUNTRIES_H_INCLUDED
#define TESTBUILDERS_WORKSHOP_TESTS_DOMAIN_COUNTRY_TEST_COUNTRIES_H_INCLUDED

#include "domain/country/Country.h"

namespace domain
{
   namespace country
   {
      const Country France("France", EURO, FRENCH);
   }
}



#endif //TESTBUILDERS_WORKSHOP_TESTS_DOMAIN_COUNTRY_TEST_COUNTRIES_H_INCLUDED